routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\AdminHome;
use App\Mission;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/missionlist', 'HomeController@show')->name('show');
Route::get('/home/admin', 'AdminController@index')->name('homeAdmin');
Route::resource('prat', 'PratController');
Route::resource('user', 'UserController');
Route::resource('mission', 'MissionController');
Route::post('mission/{id}', 'MissionController@stored')->name('givemissions');
Route::get('/home/missionlist/{n}', 'MissionDetail@detail')->name('missiondetail');
Route::post('mission/declare/{n}', 'MissionDetail@DeclareFrais')->name('declare');
Route::get('mission/page/{n}', 'MissionDetail@edit')->name('pagedeclare');
Route::get('/home/admin/fraisUser{n}', 'AdminController@FraisUser')->name('fraisuser');

resources/views/AjoutePraticien.blade.php
@extends('layouts.app')

@section('content')

@if(isset($ModificationMode))

<form method="post" action="{{route('prat.update', $DataPraticien ?? '')}}">
@csrf
@method('PATCH')
    @else
    <form action="{{route('prat.store')}}" method="post">
        @endif
        @csrf
<div class="card-header text-center">
    <div class="input-group">



<label for="NOM" class="col-md-4 col-form-label text-md-center">{{ __('NOM') }}</label>
<div class="col-md-6">
<input id="NOM" type="text" value="{{$DataPraticien->NOM??''}}" class="form-control @error('NOM') is-invalid @enderror" name="NOM" required autocomplete="NOM" autofocus> @error('NOM')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
    </span> @enderror

</div>
<br><br><br>

<label for="ETAT_CIVIL" class="col-md-4 col-form-label text-md-center">{{ __('ETAT_CIVIL') }}</label>
<div class="col-md-6">
<select class="custom-select col-md-12 col-form-label text-md-center" id="ETAT_CIVIL" name="ETAT_CIVIL">
<option selected>@if(isset($ModificationMode)){{$DataPraticien->ETAT_CIVIL??''}}@else Choisir Etat Civil @endif</option>
<option value="Mr">Mr</option>
<option value="Mme">Mme</option>
<option value="Pr">Pr</option>
<option value="Mlle">Mlle</option>
</select>
</div>
<br><br><br>



<label for="NOTE" class="col-md-4 col-form-label text-md-center">{{ __('NOTE') }}</label>
<div class="col-md-6">
<select class="custom-select col-md-12 col-form-label text-md-center" id="NOTE" name="NOTE">
<option selected>@if(isset($ModificationMode)){{$DataPraticien->NOTE??''}}@else Choisir Note @endif</option>
@php
for($i=1;$i<=20;$i++){
@endphp
    <option value={{$i}}>{{$i}}</option>
    @php
}


@endphp
</select>
</div>
<br><br><br>



<label for="NOTORIETE" class="col-md-4 col-form-label text-md-center">{{ __('NOTORIETE') }}</label>
<div class="col-md-6">
<select class="custom-select col-md-12 col-form-label text-md-center" id="NOTORIETE" name="NOTORIETE">
<option selected>@if(isset($ModificationMode)){{$DataPraticien->NOTORIETE??''}}@else Séléctionnez Notoriete @endif</option>
<option value="Très Basse">Très Basse</option>
<option value="Basse">Basse</option>
<option value="Moyenne">Moyenne</option>
<option value="Haute">Haute</option>
<option value="Très Haute">Très Haute</option>
</select>
</div>
<br><br><br>


    <label for="MEMBRE_ASSOCIATION" class="col-md-4 col-form-label text-md-center">{{ __('MEMBRE_ASSOCIATION') }}</label>
    <div class="col-md-6">
<select class="custom-select col-md-12 col-form-label text-md-center" id="MEMBRE_ASSOCIATION" name="MEMBRE_ASSOCIATION">
<option value="{{$DataPraticien->MENBRE_ASSOCIATION??''}}" selected>@if(isset($ModificationMode))   @if($DataPraticien->MENBRE_ASSOCIATION??''==1) Oui @else Non @endif @else Est-il Membre d'une Association ? @endif</option>
<option value="True">Oui</option>
<option value="False">NON</option>
</select>
    </div>
    <br><br><br>


    <label for="DIPLOME" class="col-md-4 col-form-label text-md-center">{{ __('DIPLOME') }}</label>
    <div class="col-md-6">
        <input id="DIPLOME" type="numeric" class="form-control @error('DIPLOME') is-invalid @enderror" name="DIPLOME" value="{{$DataPraticien->DIPLOME??''}}" required autocomplete="DIPLOME" autofocus> @error('DIPLOME')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span> @enderror
    </div>
    <br><br><br>
    </div>


    <div class="text-center">


    @if(isset($ModificationMode))
    <button type="submit" class="btn btn-warning">Modifier Praticien</button>
    @else
    <button type="submit" class="btn btn-success">Ajouter Praticien</button>
    @endif
    <a href="{{route('prat.index')}}" class="btn btn-warning float-right" role="button">Liste Praticien</a>
    </div>

    </div>
        </form>
    </div>

</div>
    @endsection

resources/views/ListeDesPraticiens.blade.php
@extends('layouts.app')

@section('content')

<div class="card-header">
    @if($errors->any())
<div class="alert alert-danger">
<h5>{{$errors->first()}}</h5>
</div>
@endif
@if(Session::has('succes'))
<div class="alert alert-success">
    <h5>{{ Session::get('succes')}}</h5>
</div>
@endif
    <table class="table table-striped table-dark card-body table-bordered">
<thead>
    <tr>
        <th>Nom</th>
        <th>Etat Civil</th>
        <th>Note</th>
        <th>Notoriété</th>
        <th>Membre Assoc ?</th>
        <th>Diplome</th>
        <th>Modifier/Supprimer</th>
    </tr>
</thead>
<tbody>
    @foreach ($ListePraticien as $LP)
    <tr>
    <td>{{$LP->NOM}}</td>
    <td>{{$LP->ETAT_CIVIL}}</td>
    <td>{{$LP->NOTE}}</td>
    <td>{{$LP->NOTORIETE}}</td>
    <td>
        @if($LP->MENBRE_ASSOCIATION==0)
        Non
        @else
        Oui
        @endif

    </td>
    <td>{{$LP->DIPLOME}}</td>
    <td><a href="{{route('prat.edit', $LP->ID_Praticien)}}" class="btn btn-light  float-right" role="button">Modifier</a>
        <form action="{{route('prat.destroy', $LP->ID_Praticien)}}" method="post">
            @csrf
            <input name="_method" type="hidden" value="DELETE">
            <button class="btn btn-danger"onclick="return confirm('Supprimer ce Praticien ?');" type="submit">Supprimer</button>
        </form>
    </td>
    @endforeach

    </tr>
</tbody>
    </table>
</div>


</div>
@endsection

resources/views/PageDeclare.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Declarez vos frais</div>
                <!------------------------------------->
                <form action="{{route('declare', $dec->ID_MISSION)}}" method="post" enctype="multipart/form-data">
                    @csrf

                <label for="PrixHotel" class="col-md-4 col-form-label text-md-center">{{ __('PrixHotel') }}</label>
                <div class="col-md-6">
                    <input id="PrixHotel" type="number" value="{{$pls[0]->Montant}}" class="form-control @error('PrixHotel') is-invalid @enderror" name="PrixHotel"  required autocomplete="PrixHotel" autofocus> @error('PrixHotel')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span> @enderror
                </div>

<br>

 <div class="col-md-6 custom-file" style="float:left; display:inline-block; width:60%;">
    <label for="Ticketimg" class="custom-file-label">{{ __('Ticketimg') }}</label>
     <input id="Ticketimg" type="file" class="custom-file-input @error('Ticketimg') is-invalid @enderror" name="Ticketimg" @if($ImgData[0] == '') required @endif enctype="multipart/form-data" autocomplete="Ticketimg" autofocus> @error('custom-file')
     <span class="invalid-feedback" role="alert">
         <strong>{{ $message }}</strong>
  </span> @enderror
 </div>

 @if($ImgData[0]!= '')
 <div class="card text-white bg-dark mb-3" style="max-width: 540px; margin-left:60%; display:inline-block; width:40%;">
    <div class="row no-gutters">
      <div class="col-md-4">
      <img src="{{asset("$ImgData[0]")}}" class="card-img" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text">Image actuelle pour frais d'hotel</p>
        </div>
      </div>
    </div>
  </div>

 @endif

<br>
<label for="PrixCarbu" class="col-md-4 col-form-label text-md-center">{{ __('PrixCarbu') }}</label>
<div class="col-md-6">
    <input id="PrixCarbu" type="number" value="{{$pls[1]->Montant}}" class="form-control @error('PrixCarbu') is-invalid @enderror" name="PrixCarbu"  required autocomplete="PrixCarbu" autofocus> @error('PrixCarbu')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
    </span> @enderror
</div>
<br>



<div class="col-md-6 custom-file">
    <label for="ticketcarbu" class="custom-file-label">{{ __('ticketcarbu') }}</label>
     <input id="ticketcarbu" type="file" class="custom-file-input @error('ticketcarbu') is-invalid @enderror" name="ticketcarbu" @if($ImgData[1] == '') required @endif enctype="multipart/form-data" autocomplete="Ticketimg" autofocus> @error('ticketcarbu')
     <span class="invalid-feedback" role="alert">
         <strong>{{ $message }}</strong>
  </span> @enderror
 </div>
<br>

@if($ImgData[1]!= '')
<div class="card text-white bg-dark mb-3" style="max-width: 540px; margin-left:60%; display:inline-block; width:40%;">
   <div class="row no-gutters">
     <div class="col-md-4">
     <img src="{{asset("$ImgData[1]")}}" class="card-img" alt="...">
     </div>
     <div class="col-md-8">
       <div class="card-body">
         <p class="card-text">Image actuelle pour frais de carburant</p>
       </div>
     </div>
   </div>
 </div>

@endif




<label for="PrixManger" class="col-md-4 col-form-label text-md-center">{{ __('PrixManger') }}</label>
<div class="col-md-6">
    <input id="PrixManger" type="number" value="{{$pls[2]->Montant}}" class="form-control @error('PrixManger') is-invalid @enderror" name="PrixManger"  required autocomplete="PrixManger" autofocus> @error('PrixManger')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
 </span> @enderror
</div>
<br><br>






<div class="col-md-6 custom-file">
    <label for="ticketmanger" class="custom-file-label">{{ __('ticketmanger') }}</label>
     <input id="ticketmanger" type="file" class="custom-file-input @error('ticketmanger') is-invalid @enderror" name="ticketmanger" @if($ImgData[2] == '') required @endif enctype="multipart/form-data" autocomplete="ticketmanger" autofocus> @error('ticketmanger')
     <span class="invalid-feedback" role="alert">
         <strong>{{ $message }}</strong>
  </span> @enderror
 </div>
<br>

@if($ImgData[2]!= '')
<div class="card text-white bg-dark mb-3" style="max-width: 540px; margin-left:60%; display:inline-block; width:40%;">
   <div class="row no-gutters">
     <div class="col-md-4">
     <img src="{{asset("$ImgData[2]")}}" class="card-img" alt="...">
     </div>
     <div class="col-md-8">
       <div class="card-body">
         <p class="card-text">Image actuelle pour frais de nouriture</p>
       </div>
     </div>
   </div>
 </div>

@endif

<br>




 {{-- <label for="Ticketimg" class="col-md-4 col-form-label text-md-center">{{ __('Ticketimg') }}</label>
 <div class="col-md-6">
     <input id="Ticketimg" type="file" class="custom-file-label @error('Ticketimg') is-invalid @enderror" name="Ticketimg"  required autocomplete="Ticketimg" autofocus> @error('custom-file')
     <span class="invalid-feedback" role="alert">
         <strong>{{ $message }}</strong>
  </span> @enderror
 --}}

<br><br>

 @if($pls[0]->Montant == 0)
 <button type="submit" class="btn btn-success"> Valider </button>
 @else
 <button type="submit" class="btn btn-warning"> Sauvegarder Changement </button>
 @endif

</form>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged as admin !
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/homeAdmin.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card" id="test4">
                <div class="card-header">Dashboard</div>

                <div class="card-body" id="Plgrand">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    @csrf
                    You are in home as Admin !
                    @if(Session::has('succes'))
                    <div class="alert alert-success">
                        {{ Session::get('succes')}}
                    </div>
                    @endif
                    </br>
                    Liste des Utilisateurs

                    <table class="table table-striped table-dark card-body table-bordered" id="tailleTab">
                        <thead>
                            <tr>
                                <th>Numero Matricule</th>
                                <th>Nom</th>
                                <th>Prenom</th>
                                <th>Rue</th>
                                <th>Code Postal</th>
                                <th>Ville</th>
                                <th>Adresse mail</th>
                                <th>voir Frais User</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $resp)

                            <tr>
                                <td>{{$resp->MATRICULE}}</td>
                                <td>{{$resp->NOM}}</td>
                                <td>{{$resp->PRENOM}}</td>
                                <td>{{$resp->RUE}}</td>
                                <td>{{$resp->CP}}</td>
                                <td>{{$resp->VILLE}}</td>
                                <td>{{$resp->email}}</td>
                                <td>
                                    @if($resp->id_role==1)
                                    <a href="{{route('fraisuser', $resp->ID_PERSONNELS)}}" class="btn btn-light  float-right" role="button">Frais</a></td>
                                    @endif
                                <td>




                                    @if($resp->id_role==1)
                                    <form action="{{action('UserController@destroy', $resp['ID_PERSONNELS'])}}" method="post">
                                        @csrf
                                        <input name="_method" type="hidden" value="DELETE">
                                        <button class="btn btn-danger"onclick="return confirm('Supprimer cet Utilisateur ? toute ces Mission seront aussi supprimées !');" type="submit">Supprimer</button>
                                    </form>

                                </td>

                                @endif
                                <td>
                                    @if($resp->id_role ==1)
                                    <!-- Button trigger modal -->
                                <button type="button" class="btn btn-light"  data-toggle="modal" data-target="#MODAL-{{$resp->ID_PERSONNELS}}">
                                        Ajoute Mission.

                                    </button>

                                    @else
                                    No Way, it is Admin
                                    @endif
                                    <!-- Modal -->
                                    <div class="modal fade" data-id="$resp->ID_PERSONNELS" id="MODAL-{{$resp->ID_PERSONNELS}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Ajouter une Mission à Monsieur {{$resp->NOM}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form action="{{route('givemissions',$resp->ID_PERSONNELS)}}" method="post">
                                                    @csrf
                                                    <div class="modal-body  justify-content-center">
                                                        <!----------------------------------Body---------------------------------------------->
                                                        <label for="NOM" class="col-md-4 col-form-label text-md-center">{{ __('NOM') }}</label>
                                                        <div class="col-md-6">
                                                            <input id="NOM" type="text" class="form-control @error('NOM') is-invalid @enderror" name="NOM" required autocomplete="NOM" autofocus> @error('NOM')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span> @enderror

                                                        </div>


                                                        <label for="DATE_MISSION" class="col-md-4 col-form-label text-md-center">{{ __('DATE_MISSION') }}</label>
                                                        <div class="col-md-6">
                                                            <input id="DATE_MISSION" type="date" class="form-control @error('DATE_MISSION') is-invalid @enderror" name="DATE_MISSION" required autocomplete="DATE_MISSION" autofocus> @error('DATE_MISSION')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span> @enderror

                                                        </div>




                                                        <label for="RUE" class="col-md-4 col-form-label text-md-center">{{ __('RUE') }}</label>
                                                        <div class="col-md-6">
                                                            <input id="RUE" type="text" class="form-control @error('RUE') is-invalid @enderror" name="RUE" required autocomplete="RUE" autofocus> @error('RUE')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span> @enderror

                                                        </div>





                                                        <label for="VILLE" class="col-md-4 col-form-label text-md-center">{{ __('VILLE') }}</label>
                                                        <div class="col-md-6">
                                                            <input id="VILLE" type="text" class="form-control @error('RUE') is-invalid @enderror" name="VILLE" required autocomplete="VILLE" autofocus> @error('VILLE')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span> @enderror

                                                        </div>



                                                        <label for="DescriptionMission" class="col-md-4 col-form-label text-md-center">{{ __('DescriptionMission') }}</label>
                                                        <div class="col-md-6">
                                                            <input id="DescriptionMission" type="text" class="form-control @error('RUE') is-invalid @enderror" name="DescriptionMission" required autocomplete="DescriptionMission" autofocus> @error('DescriptionMission')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span> @enderror

                                                        </div>


                                                          <label for="ID_Praticien" class="col-md-4 col-form-label text-md-center">{{ __('ID_Praticien') }}</label>
                                                            <div class="col-md-6">
                                                        <select class="custom-select col-md-12 col-form-label text-md-center" id="ID_Praticien" name="ID_Praticien">
                                                    <option selected>Choisir Praticien !</option>
                                                    @foreach($praticiens as $ListPrate)
                                                        <option value="{{$ListPrate->NOM}}">{{$ListPrate->NOM}}</option>
                                                   @endforeach
                                                </select>
                                                            </div>
                                                        <!--------------------------------End----Body------------------------------------>


                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                                        <button type="submit" class="btn btn-primary">Ajouter Mission</button>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>



                            </tr>
                        </tbody> @endforeach
                    </table>
                </div>

            </div>

        </div>

    </div>
</div>
</div>
<style>
    #test4{
    width: 150%;


          }
          #Plgrand{
             float: left;
          }

    </style>
@endsection @csrf

resources/views/listefrais.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    @csrf
                    Liste des frais de Monsieur <strong>{{$users->NOM}}</strong>
                    <br>
                    <br>
                    <br>

                        @php
                        $test = 0;
                        @endphp
                        @foreach ($fraiss as $frais)
                        <div class="text-center">

                        @if($frais->ID_NOTE_DE_FRAIS==31)

                        <p>Mission Numero {{$frais->ID_MISSION}} : Aucun frais Déclaré</p>
                        @else


                        <br><br>
                        <strong> Mission Numero {{$frais->ID_MISSION}}

                             Date depot Frais : {{$frais->datedepot}}.
                            <br>
                            Type frais : {{$frais->TypeHotel}}, Montant de ce frais : {{$frais->Montant}}.
                            <br>
                            Type frais : {{$frais->TypeCarburant}}, Montant de ce frais : {{$frais->MontantCarburant}}.
                            <br>
                            Type frais : {{$frais->TypeManger}}, Montant de ce frais : {{$frais->MontantManger}}.<br>
                            @php

                            $somme = $frais->Montant+$frais->MontantCarburant+$frais->MontantManger;
                            echo 'somme pour cette Mission : = '.$somme;

                            $test =$test+$somme;

                            @endphp
                            <br><br>
                            @if($frais->TicketHotel != null)
                            <div class="card-group">
                                <div class="card"><img src="{{asset("$frais->TicketHotel")}}" class="card-img w-100 d-flex">
                                    <div class="card-body">

                                        <p class="card-text">Cliquez en dessous</p><a class="btn btn-primary" href="{{asset("$frais->TicketHotel")}}" download type="button">Télécharger !</a></div>
                                </div>
                            <div class="card"><img src="{{asset("$frais->TicketCarbu")}}" class="card-img w-100 d-flex">
                                    <div class="card-body">
                                        <h4 class="card-title">Preuve de Frais</h4>
                                    <p class="card-text">Cliquez sur les bouttons ce-dessous pour télécharger les preuves de payement. </p><a class="btn btn-primary" href="{{asset("$frais->TicketCarbu")}}" download type="button">Télécharger !</a></div>
                                </div>
                                <div class="card"><img src="{{asset("$frais->TicketManger")}}" class="card-img w-100 d-flex">
                                    <div class="card-body">

                                        <p class="card-text">Cliquez en dessous</p><a class="btn btn-primary" href="{{asset("$frais->TicketManger")}}" download type="button">Télécharger !</a></div>
                                </div>
                            </div>
                            <script src="assets/js/jquery.min.js"></script>
                            <script src="assets/bootstrap/js/bootstrap.min.js"></script>
                            @else
                            <p class="card-text"> Image non Disponible.</p>
                            @endif

                            <br>


                             </div>
                        </strong>

                    @endif
                    @endforeach
                    <br>
                    <br>
                    <br>
                    <div class="text-center">
                        <h3><strong>
                                @php
                                echo 'somme totale du visiteur medical ='.$test;
                                @endphp
                            </strong>
                        </h3>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/missDetail.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-body">
                <h2 class="card-title"> @foreach($missionloop as $test)
                    Voici le detail de votre Mission Monsieur  <strong>{{$test->Nom_Personnel}}</strong>
                  @endforeach
                </h2>
            </div>
            </div>

<!-----------------------------------------Localisation--------------------------------------------------------------------------------->

            <div class="card">
                <h3 class="card-header">
                    Lieu de Mission
                </h3>
                <div class="card-body">

                    @foreach($missionloop as $test)<h5>
                    Nom et Numero de rue : <strong>{{$test->RUE}}</strong><br><br>
                    Ville : <strong>{{$test->VILLE}}</strong>
                    </h5>
                    @endforeach
                </div>

                </div>

<!------------------------------------------------Praticien------------------------------------------------------------------------------------->

<div class="card">
    <h3 class="card-header">
        Informations Praticien :
    </h3>
    <div class="card-body">

        @foreach($missionloop as $test)
   <h5>
            Nom et titre du Praticien: <strong>{{$test->Nom_Praticien}}</strong><br><br>
        Etat civil: <strong>{{$test->ETAT_CIVIL}}</strong><br><br>
        Note du Praticien sur 20: <strong>{{$test->NOTE}}</strong>   NB : plus la note est élevée plus il sera enclin à acheter les produits du laboratoire<br><br>
        Notoriété: <strong>{{$test->NOTORIETE}}</strong><br><br>
        Le praticien est il membre d'une Association :<strong> @if($test->MENBRE_ASSOCIATION == 0) Non @else Oui @endif</strong><br><br>
        Diplome du Praticien : <strong>{{$test->DIPLOME}}</strong><br>
    </h5>
        @endforeach
    </div>

    </div>
<!--------------------------------------------------------------------------------------------------------------------------->





<div class="card">
    <h3 class="card-header">
        Mission:
    </h3>
    <div class="card-body">

        @foreach($missionloop as $test)
       <h5> Nom de la Mission: <strong>{{$test->Nom_Mission}}</strong><br><br>
        Date de la Mission: <strong>{{$test->DATE_MISSION}}</strong><br><br>
        Description Complete de la Mission: <strong>{{$test->DescriptionMission}}</strong><br><br>

        @endforeach
    </div>

    </div>



<!--------------------------------------------------------------------------------------------------------------------------->
<a href="{{  route('pagedeclare', $test->ID_MISSION) }}" class="btn btn-info float-right" role="button">Déclarez Vos Frais</a>
        </div>
    </div>
</div>
@endsection